window.SAFETY_NUDGES_ALPHA_SIGNUP_ENDPOINT = window.SAFETY_NUDGES_ALPHA_SIGNUP_ENDPOINT || "https://bjokhkmomdogymmmnpdo.supabase.co/functions/v1/safety-nudges-alpha-signup";
window.SAFETY_NUDGES_ALPHA_TURNSTILE_SITE_KEY = window.SAFETY_NUDGES_ALPHA_TURNSTILE_SITE_KEY || "0x4AAAAAADNY46ySTqwtJ3yv";
window.SAFETY_NUDGES_ALPHA_SKIP_TURNSTILE = window.SAFETY_NUDGES_ALPHA_SKIP_TURNSTILE || false;
